// Generates the preload IPC allowlists and the channel union types from the
// single-source contract in src/shared/ipc/contract.ts (plan 1.2).
//
//   node scripts/gen-ipc.mjs          -> writes the generated files
//   node scripts/gen-ipc.mjs --check  -> exits 1 when they are stale
import { mkdir, readFile, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import prettier from 'prettier';

const ROOT = process.cwd();
const CONTRACT = join(ROOT, 'src/shared/ipc/contract.ts');
const PRELOAD_OUT = join(ROOT, 'src/preload/generated.ts');
const TYPES_OUT = join(ROOT, 'src/shared/ipc/generated-types.d.ts');
const CHECK = process.argv.includes('--check');

function extractList(source, name) {
  const marker = `export const ${name} = [`;
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`${name} not found in src/shared/ipc/contract.ts`);
  const open = source.indexOf('[', start);
  const close = source.indexOf('] as const', open);
  if (close < 0) throw new Error(`${name}: malformed list in contract.ts`);
  const items = [...source.slice(open, close).matchAll(/'([^']+)'/g)].map((m) => m[1]);
  if (items.length === 0) throw new Error(`${name}: empty list in contract.ts`);
  return items;
}

async function format(code, filepath) {
  const options = (await prettier.resolveConfig(filepath)) ?? {};
  return prettier.format(code, { ...options, filepath });
}

const source = await readFile(CONTRACT, 'utf-8');
const invoke = extractList(source, 'INVOKE_CHANNELS');
const send = extractList(source, 'SEND_CHANNELS');
const receive = extractList(source, 'RECEIVE_CHANNELS');

const header = `// AUTO-GENERATED by scripts/gen-ipc.mjs from src/shared/ipc/contract.ts.
// Do not edit manually — change the contract and run \`npm run ipc:gen\`.`;

const setConst = (name, list) =>
  `export const ${name}: ReadonlySet<string> = new Set([${list.map((c) => `'${c}'`).join(', ')}]);`;

const union = (name, list) =>
  `export type ${name} =\n  | ${list.map((c) => `'${c}'`).join('\n  | ')};`;

const preloadCode = `${header}

${setConst('ALLOWED_INVOKE_CHANNELS', invoke)}

${setConst('ALLOWED_SEND_CHANNELS', send)}

${setConst('ALLOWED_RECEIVE_CHANNELS', receive)}
`;

const typesCode = `${header}

${union('IpcInvokeChannel', invoke)}

${union('IpcSendChannel', send)}

${union('IpcReceiveChannel', receive)}
`;

const outputs = [
  [PRELOAD_OUT, await format(preloadCode, PRELOAD_OUT)],
  [TYPES_OUT, await format(typesCode, TYPES_OUT)]
];

let stale = false;
for (const [path, code] of outputs) {
  let current = null;
  try {
    current = await readFile(path, 'utf-8');
  } catch {
    current = null;
  }
  if (current === code) continue;
  stale = true;
  if (!CHECK) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, code, 'utf-8');
  }
}

const summary = `${invoke.length} invoke, ${send.length} send, ${receive.length} receive`;

if (CHECK) {
  if (stale) {
    console.error(`ipc:gen: generated files are stale (${summary}); run "npm run ipc:gen".`);
    process.exit(1);
  }
  console.log(`ipc:gen: up to date (${summary})`);
} else {
  console.log(
    `ipc:gen: ${summary} → src/preload/generated.ts, src/shared/ipc/generated-types.d.ts`
  );
}
