import { installIpcGuards } from './guard';
import { registerMusicBrainzHandlers } from './musicbrainz';
import { registerFsHandlers } from './fs/fs-handlers';
import { registerLibraryHandlers } from './library/library-handlers';
import { registerSettingsHandlers } from './settings/settings-handlers';
import { registerMediaHandlers } from './media/media-handlers';
import { registerCoverHandlers } from './cover/cover-handlers';
import { registerSubtitleHandlers } from './subtitle-handlers';
import { registerPlaybackHandlers } from './playback-handlers';
import { registerDependencyHandlers } from './dependency/dependency-handlers';
import { registerYoutubeHandlers } from './youtube/youtube-handlers';
import { registerSoundcloudHandlers } from './soundcloud/soundcloud-handlers';
import { registerYoutubeAuthHandlers } from './youtube/youtube-auth-handlers';
import { registerSubscriptionHandlers } from './subscriptions/subscriptions-handlers';
import { registerDownloadHandlers } from './downloads/downloads-handlers';
import { registerDownloadProfileHandlers } from './downloads/download-profiles';
import { registerDialogHandlers } from './dialog-handlers';
import { registerDiagnosticsHandlers } from './diagnostics-handlers';
import { registerUpdaterHandlers } from './updater-handlers';
import { registerSourcesHandlers } from './sources/sources-handlers';
import { registerPreviewHandlers } from '../preview/preview-window';
import { registerSavedHandlers } from './saved-streams';
import { registerRadioHandlers } from './radio-store';
import { registerPluginsHandlers } from './plugins/plugins-handlers';
import { registerRemoteImageHandler } from './remote-image';
import { registerCacheHandlers } from './cache-handlers';
import { registerFactoryResetHandler } from './factory-reset';

export function registerIPC(): void {
  installIpcGuards();
  registerFsHandlers();
  registerLibraryHandlers();
  registerSettingsHandlers();
  registerMediaHandlers();
  registerCoverHandlers();
  registerSubtitleHandlers();
  registerPlaybackHandlers();
  registerDependencyHandlers();
  registerYoutubeHandlers();
  registerSoundcloudHandlers();
  registerYoutubeAuthHandlers();
  registerSubscriptionHandlers();
  registerDownloadHandlers();
  registerDownloadProfileHandlers();
  registerDialogHandlers();
  registerMusicBrainzHandlers();
  registerDiagnosticsHandlers();
  registerUpdaterHandlers();
  registerSourcesHandlers();
  registerPreviewHandlers();
  registerSavedHandlers();
  registerRadioHandlers();
  registerPluginsHandlers();
  registerRemoteImageHandler();
  registerCacheHandlers();
  registerFactoryResetHandler();
}
