import { installIpcGuards } from './guard';
import { registerMusicBrainzHandlers } from './musicbrainz';
import { registerFsHandlers } from './fs-handlers';
import { registerLibraryHandlers } from './library-handlers';
import { registerSettingsHandlers } from './settings-handlers';
import { registerMediaHandlers } from './media-handlers';
import { registerCoverHandlers } from './cover-handlers';
import { registerSubtitleHandlers } from './subtitle-handlers';
import { registerPlaybackHandlers } from './playback-handlers';
import { registerDependencyHandlers } from './dependency-handlers';
import { registerYoutubeHandlers } from './youtube-handlers';
import { registerYoutubeAuthHandlers } from './youtube-auth-handlers';
import { registerSubscriptionHandlers } from './subscriptions-handlers';
import { registerDownloadHandlers } from './downloads-handlers';
import { registerDownloadProfileHandlers } from './download-profiles';
import { registerDialogHandlers } from './dialog-handlers';
import { registerDiagnosticsHandlers } from './diagnostics-handlers';
import { registerUpdaterHandlers } from './updater-handlers';
import { registerSourcesHandlers } from './sources-handlers';
import { registerSavedHandlers } from './saved-streams';
import { registerRadioHandlers } from './radio-store';

export function registerIPC(): void {
  installIpcGuards();
  registerFsHandlers();
  registerLibraryHandlers();
  registerSettingsHandlers();
  registerMediaHandlers();
  registerCoverHandlers();
  registerSubtitleHandlers();
  registerPlaybackHandlers();
  registerDependencyHandlers();
  registerYoutubeHandlers();
  registerYoutubeAuthHandlers();
  registerSubscriptionHandlers();
  registerDownloadHandlers();
  registerDownloadProfileHandlers();
  registerDialogHandlers();
  registerMusicBrainzHandlers();
  registerDiagnosticsHandlers();
  registerUpdaterHandlers();
  registerSourcesHandlers();
  registerSavedHandlers();
  registerRadioHandlers();
}
